# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Movie.destroy_all
movies = Movie.create([{image:"https://upload.wikimedia.org/wikipedia/en/5/5a/It_%282017%29_poster.jpg", title:"It", sum:"Seven young outcasts in Derry, Maine, are about to face their worst nightmare -- an ancient, shape-shifting evil that emerges from the sewer every 27 years to prey on the town's children. Banding together over the course of one horrifying summer, the friends must overcome their own personal fears to battle the murderous, bloodthirsty clown known as Pennywise.", release_year: 2018},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/1/1f/Conjuring_poster.jpg/220px-Conjuring_poster.jpg", title:"The Conjuring", sum:"In 1970, paranormal investigators and demonologists Lorraine (Vera Farmiga) and Ed (Patrick Wilson) Warren are summoned to the home of Carolyn (Lili Taylor) and Roger (Ron Livingston) Perron. The Perrons and their five daughters have recently moved into a secluded farmhouse, where a supernatural presence has made itself known.", release_year:2013},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Conjuring_2.jpg/220px-Conjuring_2.jpg", title:"The Conjuring 2", sum:"In 1977, paranormal investigators Ed and Lorraine Warren travel to Enfield where they meet Peggy Hodgson, an overwhelmed single mother of four who tells the couple that something evil is in her home. Ed and Lorraine believe her story. As the Warrens try to help the besieged girl, they become the next targets of the malicious spirit.", release_year:2016},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Paranormal_Activity_poster.jpg/220px-Paranormal_Activity_poster.jpg", title:"Paranormal Activity", sum:"Soon after moving into a suburban tract home, Katie (Katie Featherston) and Micah (Micah Sloat) become increasingly disturbed by what appears to be a supernatural presence. Hoping to capture evidence of it on film, they set up video cameras in the house but are not prepared for the terrifying events that follow.", release_year:2007},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Insidious_poster.jpg/220px-Insidious_poster.jpg", title:"Insidious", sum:"Parents (Patrick Wilson, Rose Byrne) take drastic measures when it seems their new home is haunted and their comatose son (Ty Simpkins) is possessed by a malevolent entity.", release_year:2010},
{image:"https://i2.wp.com/bloody-disgusting.com/horrordb/wp-content/uploads/2017/02/ewi7gYW22t8T3piRvrXO73GlzuL.jpg?fit=200%2C300", title:"Scream", sum:"Wes Craven re-invented and revitalised the slasher-horror genre with this modern horror classic, which manages to be funny, clever and scary, as a fright-masked knife maniac stalks high-school students in middle-class suburbia. Craven is happy to provide both tension and self-parody as the body count mounts - but the victims aren't always the ones you'd expect.", release_year:1996},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Halloween_%281978%29_theatrical_poster.jpg/220px-Halloween_%281978%29_theatrical_poster.jpg", title:"Halloween", sum:"On a cold Halloween night in 1963, six year old Michael Myers brutally murdered his 17-year-old sister, Judith. He was sentenced and locked away for 15 years. But on October 30, 1978, while being transferred for a court date, a 21-year-old Michael Myers steals a car and escapes Smith's Grove. He returns to his quiet hometown of Haddonfield, Illinois, where he looks for his next victims.", release_year:1978},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/TheOthers.jpg/220px-TheOthers.jpg", title:"The Others", sum:"A woman who lives in her darkened old family house with her two photosensitive children becomes convinced that the home is haunted. A woman named Grace retires with her two children to a mansion on Jersey, towards the end of the Second World War, where she's waiting for her husband to come back from battle.", release_year:2001},
{image:"https://upload.wikimedia.org/wikipedia/en/9/90/Annabelle_film_poster.jpg", title:"Annabelle", sum:"John Form (Ward Horton) thinks he's found the perfect gift for his expectant wife, Mia (Annabelle Wallis) : a vintage doll in a beautiful white dress. However, the couple's delight doesn't last long: Little do they know, the doll is possesed and is now a sinister presence lurking around their home.", release_year:2014},
{image:"https://upload.wikimedia.org/wikipedia/en/3/34/TheNunPoster.jpg", title:"The Nun", sum:"When a young nun at a cloistered abbey in Romania takes her own life, a priest with a haunted past and a novitiate on the threshold of her final vows are sent by the Vatican to investigate. Together, they uncover the order's unholy secret. Risking not only their lives but their faith and their very souls, they confront a malevolent force in the form of a demonic nun.", release_year:2018 },
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/The_Witch_poster.png/220px-The_Witch_poster.png", title:"THe Witch", sum:"In 1630 New England, panic and despair envelops a farmer, his wife and their children when youngest son Samuel suddenly vanishes. The family blames Thomasin, the oldest daughter who was watching the boy at the time of his disappearance. With suspicion and paranoia mounting, twin siblings Mercy and Jonas suspect Thomasin of witchcraft, testing the clan's faith, loyalty and love to one another.", release_year:2015},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/f/f8/SinisterMoviePoster2012.jpg/220px-SinisterMoviePoster2012.jpg", title:"Sinister", sum:"True-crime writer Ellison Oswald (Ethan Hawke) is in a slump; he hasn't had a best seller in more than 10 years and is becoming increasingly desperate for a hit. So, when he discovers the existence of a snuff film showing the deaths of a family, he vows to solve the mystery. He moves his own family into the victims' home and gets to work. However, when old film footage and other clues hint at the presence of a supernatural force, Ellison learns that living in the house may be fatal.", release_year:2012},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/f/fa/A_Nightmare_on_Elm_Street_%281984%29_theatrical_poster.jpg/220px-A_Nightmare_on_Elm_Street_%281984%29_theatrical_poster.jpg", title:"The Nightmare on Elm Street", sum:"In Wes Craven's classic slasher film, several Midwestern teenagers fall prey to Freddy Krueger (Robert Englund), a disfigured midnight mangler who preys on the teenagers in their dreams -- which, in turn, kills them in reality.", release_year:1984},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/Poltergeist_%281982%29.png/220px-Poltergeist_%281982%29.png", title:"Poltergeist", sum:"Strange and creepy happenings beset an average California family, the Freelings -- Steve (Craig T. Nelson), Diane (JoBeth Williams), teenaged Dana (Dominique Dunne), eight-year-old Robbie (Oliver Robins), and five-year-old Carol Ann (Heather O'Rourke) -- when ghosts commune with them through the television set.", release_year:1982},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Exorcist_ver2.jpg/220px-Exorcist_ver2.jpg", title:"The Exorcist", sum:"One of the most profitable horror movies ever made, this tale of an exorcism is based loosely on actual events. When young Regan (Linda Blair) starts acting odd -- levitating, speaking in tongues -- her worried mother (Ellen Burstyn) seeks medical help, only to hit a dead end. A local priest (Jason Miller), however, thinks the girl may be seized by the devil.", release_year:1973},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/The_Amityville_Horror_poster.JPG/220px-The_Amityville_Horror_poster.JPG", title:"The Amityville Horror", sum:"When George Lutz (Ryan Reynolds) and his wife, Kathy (Melissa George), find a beautiful new house in the small town of Amityville, N.Y., they think the place is too good to be true. After they move in with their kids, they find out the cheap price tag is thanks to the house's sordid history: The former tenant murdered his family after supposedly being possessed by the devil.", release_year:2005},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/Fridaythe13th2009.JPG/220px-Fridaythe13th2009.JPG", title:"Friday the 13th", sum:"Against the advice of locals and police, Clay (Jared Padalecki) scours the eerie woods surrounding Crystal Lake for his missing sister. But the rotting cabins of an abandoned summer camp are not the only things he finds. Hockey-masked killer Jason Voorhees lies in wait for a chance to use his razor-sharp machete on Clay and the group of college students who have come to the forest to party.", release_year:2009},
{image:"https://upload.wikimedia.org/wikipedia/en/3/3d/Childs_Play.jpg", title:"Child's Play", sum:"Gunned down by Detective Mike Norris (Chris Sarandon), dying murderer Charles Lee Ray (Brad Dourif) uses black magic to put his soul inside a doll named Chucky -- which Karen Barclay (Catherine Hicks) then buys for her young son, Andy (Alex Vincent). When Chucky kills Andy's baby sitter, the boy realizes the doll is alive and tries to warn people, but he's institutionalized.", release_year:1988},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/Zodiac2007Poster.jpg/220px-Zodiac2007Poster.jpg", title:"Zodiac", sum:"In the late 1960s and 1970s, fear grips the city of San Francisco as a serial killer called Zodiac stalks its residents. Investigators (Mark Ruffalo, Anthony Edwards) and reporters (Jake Gyllenhaal, Robert Downey Jr.) become obsessed with learning the killer's identity and bringing him to justice. Meanwhile, Zodiac claims victim after victim and taunts the authorities with cryptic messages, cyphers and menacing phone calls.", release_year:2007},
{image:"https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/The-Babadook-Poster.jpg/220px-The-Babadook-Poster.jpg", title:"The Babadook", sum:"A single mother, plagued by the violent death of her husband, battles with her son's fear of a monster lurking in the house, but soon discovers a sinister presence all around her.", release_year:2014}])
